# Notebook 2: NumPy — The Computational Backbone
**DCS 404 — Data Science and Machine Learning**

---

## Learning Objectives
- Create and manipulate NumPy arrays
- Understand dtype, shape, and reshaping
- Apply vectorised operations and broadcasting
- Use NumPy for basic linear algebra
- Replace Python loops with fast array operations

## 1. Why NumPy?

Python lists are flexible but slow for numerical work because each element is a full Python object with overhead.

NumPy stores elements in a **contiguous block of typed memory** — operations run in optimised C/Fortran under the hood.

| Task | Python list | NumPy array |
|------|-------------|-------------|
| Sum 10 M numbers | ~0.5 s | ~0.01 s |
| Element-wise multiply | requires loop | single expression |
| Linear algebra | manual | built-in |

> **Rule**: if you are writing a numeric loop in Python, there is almost certainly a NumPy one-liner for it.

In [1]:
import numpy as np

# Creating arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1,2,3],[4,5,6]], dtype=np.float32)

print('1-D array :', a)
print('Shape     :', a.shape)
print('2-D array :\n', b)
print('Shape     :', b.shape, '  dtype:', b.dtype)

# Factory functions
print('\nzeros(3,4):\n', np.zeros((3,4)))
print('arange(0,10,2):', np.arange(0,10,2))
print('linspace(0,1,5):', np.linspace(0,1,5))

1-D array : [1 2 3 4 5]
Shape     : (5,)
2-D array :
 [[1. 2. 3.]
 [4. 5. 6.]]
Shape     : (2, 3)   dtype: float32

zeros(3,4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
arange(0,10,2): [0 2 4 6 8]
linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]


## 2. Indexing and Slicing

NumPy slicing is just like Python slicing, but extended to multiple dimensions.

```
arr[row_slice, col_slice]
```

Boolean indexing lets you filter rows by a condition.

In [2]:
m = np.arange(16).reshape(4, 4)
print('Matrix:\n', m)
print('Row 1       :', m[1])
print('Col 2       :', m[:, 2])
print('Sub-matrix  :\n', m[1:3, 1:3])
print('Top-right   :', m[0, -1])

# Boolean indexing
print('Elements > 9:', m[m > 9])
# Fancy indexing
print('Rows 0 and 3:\n', m[[0, 3]])

Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Row 1       : [4 5 6 7]
Col 2       : [ 2  6 10 14]
Sub-matrix  :
 [[ 5  6]
 [ 9 10]]
Top-right   : 3
Elements > 9: [10 11 12 13 14 15]
Rows 0 and 3:
 [[ 0  1  2  3]
 [12 13 14 15]]


## 3. Vectorised Operations and Broadcasting

**Vectorisation**: applying an operation to an entire array at once — no explicit loops.

**Broadcasting**: NumPy automatically expands smaller arrays to match larger ones:

```
(4, 3) + (3,)  →  broadcasts (3,) to (4, 3) — adds to every row
```

In [3]:
import time

N = 5_000_000
python_list = list(range(N))
np_arr = np.arange(N, dtype=np.float64)

t0 = time.time()
python_result = [x**2 for x in python_list]
print(f'Python loop : {time.time()-t0:.3f}s')

t0 = time.time()
np_result = np_arr ** 2
print(f'NumPy       : {time.time()-t0:.3f}s')

# Broadcasting demo
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
bias = np.array([10, 20, 30])
print('\nA + bias (broadcasting):\n', A + bias)

Python loop : 0.102s
NumPy       : 0.006s

A + bias (broadcasting):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


## 4. Common NumPy Functions

NumPy ships with hundreds of mathematical functions — all vectorised.

In [4]:
rng = np.random.default_rng(seed=42)
data = rng.normal(loc=50, scale=10, size=(100,))

print(f'Mean   : {np.mean(data):.2f}')
print(f'Std    : {np.std(data):.2f}')
print(f'Min    : {np.min(data):.2f}')
print(f'Max    : {np.max(data):.2f}')
print(f'Median : {np.median(data):.2f}')
print(f'25th % : {np.percentile(data, 25):.2f}')

# Sorting and argsort
small = np.array([3, 1, 4, 1, 5, 9, 2])
print('\nSorted         :', np.sort(small))
print('Argsort indices:', np.argsort(small))
print('Top-3 values   :', small[np.argsort(small)[-3:]])

Mean   : 49.50
Std    : 7.73
Min    : 30.49
Max    : 71.42
Median : 49.98
25th % : 44.56

Sorted         : [1 1 2 3 4 5 9]
Argsort indices: [1 3 6 0 2 4 5]
Top-3 values   : [4 5 9]


## 5. Linear Algebra with NumPy

Linear algebra is at the heart of machine learning — weights, activations, covariance matrices, and more.

In [5]:
A = np.array([[2., 1.], [5., 3.]])
b_vec = np.array([8., 21.])

# Matrix-vector multiply
print('A @ b :', A @ b_vec)

# Solving Ax = b
x = np.linalg.solve(A, b_vec)
print('Solution x:', x)
print('Verify Ax = b:', np.allclose(A @ x, b_vec))

# Eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(A)
print('\nEigenvalues:', eigenvalues)

# SVD (used in PCA and dimensionality reduction)
U, S, Vt = np.linalg.svd(A)
print('Singular values:', S)

# Dot product vs element-wise
v1 = np.array([1., 2., 3.])
v2 = np.array([4., 5., 6.])
print('\nDot product  :', np.dot(v1, v2))
print('Element-wise :', v1 * v2)

A @ b : [ 37. 103.]
Solution x: [3. 2.]
Verify Ax = b: True

Eigenvalues: [0.20871215 4.79128785]
Singular values: [6.24294338 0.16018085]

Dot product  : 32.0
Element-wise : [ 4. 10. 18.]


## 6. Reshaping and Stacking

In [6]:
arr = np.arange(24)
print('Original  :', arr.shape)
print('(2,3,4)   :\n', arr.reshape(2,3,4))
print('(6,4)     :\n', arr.reshape(6,4))
print('Flatten   :', arr.reshape(4,6).flatten().shape)

# Stacking
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print('\nvstack:\n', np.vstack([a,b]))
print('hstack:\n', np.hstack([a,b]))

Original  : (24,)
(2,3,4)   :
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(6,4)     :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Flatten   : (24,)

vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack:
 [[1 2 5 6]
 [3 4 7 8]]


## Exercises

1. Create a 5×5 identity matrix using `np.eye`. Then multiply it by 7 and verify the result.
2. Generate 1 000 samples from a standard normal distribution. Compute the Z-scores: `z = (x - mean) / std`. Confirm the Z-scores have mean ≈ 0 and std ≈ 1.
3. Without using a loop, compute the Euclidean distance between every pair of rows in a (4, 3) matrix. *Hint*: Broadcasting.
4. Given a 2D array of exam scores (shape `(30, 5)`), find the student (row) with the highest average score.

## Reflection Questions
- Why does NumPy store data in a contiguous memory block? What advantage does that give over Python lists?
- What happens when you slice a NumPy array — do you get a copy or a view? Why does this matter?

---
**Next →** `03_pandas_essentials.ipynb`